import {
  type ReactNode,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

import { getSignupData, signup } from "../api/registration";
import { useAuth } from "../auth/AuthenticatedContext";
import { Environment, getConfig } from "../config/config";
import { MEDIUM_INTERVAL, SHORT_INTERVAL, SUPPORT_EMAIL } from "../const";
import { ApiError } from "../error/ApiError";
import { UserFacingError } from "../error/UserFacingError";
import { type User } from "../types";
import type { BootstrapData } from "../types/main";
import { errorMessage } from "../utils/common";
import logger from "../utils/logger";
import {
  mapFetchUserErrorToErrorMessage,
  mapUserStatusToSignupPhase,
} from "../utils/register-utils";
import { isAbortError, isTransient, withRetry } from "../utils/retry";
import { UserContext } from "./UserContext";
import { useRecaptcha } from "./useRecaptcha";
import { UserSignupPhase } from "./userSignupPhase";

export function UserProvider({
  children,
  bootstrapData,
}: {
  children: ReactNode;
  bootstrapData: BootstrapData;
}) {
  const config = getConfig();
  const isProd = config.environment === Environment.PRODUCTION;
  useRecaptcha(isProd);

  // User authentication status.
  const { authenticated: isUserAuthenticated } = useAuth();

  const [user, setUser] = useState<User | undefined>(undefined);
  const [userSignupPhase, setUserSignupPhase] = useState<UserSignupPhase>(
    UserSignupPhase.INITIAL_FETCH,
  );

  // Keep track of the last user facing error that was generated by the
  // provider. The errors are only going to be shown in the landing page and
  // by a little infobox, not toast alerts, so showing the last one is enough.
  const [lastError, setLastError] = useState<UserFacingError | undefined>(
    undefined,
  );

  /**
   * Defines how many times we are going to retry fetching for the user's
   * signup on transient errors before giving up.
   */
  const maxTransientErrorRetries: number = 3;

  /**
   * User reference to avoid rerender in case we fetch the user from the
   * backend and it hasn't changed at all.
   */
  const userRef = useRef<User | undefined>(undefined);

  /**
   * Reference of the phase in which the user signup is in. It is useful so
   * that the "signupUser" function always has the freshest signup phase
   * object possible.
   */
  const userSignupPhaseRef = useRef<UserSignupPhase>(
    UserSignupPhase.INITIAL_FETCH,
  );

  /**
   * Keeps track of the last time there was a change in the user signup
   * status.
   */
  const lastUserSignupPhaseChangedAt = useRef<number>(0);

  /**
   * Counter to keep track of how many transient errors we have encountered
   * while polling to check for an status update of the user's signup.
   */
  const pollTransientRetriesLeft = useRef<number>(maxTransientErrorRetries);

  /**
   * Utility function so that we can keep both the user signup phase and
   * reference in sync. It just makes sure that we update both at the same
   * time.
   */
  const updateSignupPhase = useCallback((phase: UserSignupPhase) => {
    if (phase !== userSignupPhaseRef.current) {
      userSignupPhaseRef.current = phase;
      setUserSignupPhase(phase);
      lastUserSignupPhaseChangedAt.current = Date.now();
    }
  }, []);

  /**
   * Processes the result from fetching the user signup by updating the user
   * state and the signup phase. Skips the update if the user signup has not
   * changed from the previous fetch, or if the signal has been aborted.
   */
  const processSignupResult = useCallback(
    (result: User | undefined, abortSignal?: AbortSignal) => {
      // Make sure that the user has changed before changing the state and
      // scheduling a rerender.
      if (JSON.stringify(userRef.current) !== JSON.stringify(result)) {
        if (abortSignal?.aborted) {
          return;
        }
        userRef.current = result;
        if (abortSignal?.aborted) {
          return;
        }
        setUser(result);
      }

      if (abortSignal?.aborted) {
        return;
      }
      updateSignupPhase(
        mapUserStatusToSignupPhase(userSignupPhaseRef.current, result),
      );
      setLastError(undefined);
    },
    [updateSignupPhase],
  );

  /**
   * Fetches the user's signup data, critical for the application to work.
   */
  const fetchUser = useCallback(
    async (signal?: AbortSignal): Promise<void> => {
      const result: User | undefined = await getSignupData(signal);
      processSignupResult(result, signal);
    },
    [processSignupResult],
  );

  /**
   * Creates a user signup in the back end.
   */
  const signupUser = useCallback(async () => {
    if (
      !isUserAuthenticated ||
      userSignupPhaseRef.current === UserSignupPhase.BLOCKED ||
      userSignupPhaseRef.current === UserSignupPhase.SIGNING_UP ||
      userSignupPhaseRef.current === UserSignupPhase.PROVISIONING ||
      userSignupPhaseRef.current === UserSignupPhase.PROVISIONING_TIMED_OUT
    ) {
      return;
    }

    setLastError(undefined);
    updateSignupPhase(UserSignupPhase.SIGNING_UP);
    try {
      await signup();
    } catch (err) {
      // Only reset the "userSignupPhase" to "NOT_STARTED" if the status is
      // still "SIGNING_UP". We account for the edge case in which the server
      // might sign the user up, but for some reason the UI might fail. If all
      // this aligns with a polling fetch of the user, it might advance the
      // state and the statement below would reset it back to "NOT_STARTED".
      //
      // The cast is needed because TypeScript carries the stale narrowing
      // from the early return in the beginning of the function, without
      // realizing that the reference can change due to the "signup" call.
      if (
        (userSignupPhaseRef.current as UserSignupPhase) ===
        UserSignupPhase.SIGNING_UP
      ) {
        updateSignupPhase(UserSignupPhase.NOT_STARTED);
      }
      if (err instanceof ApiError) {
        logger.error(
          "Unexpected response received when attempting to create a user signup",
          err,
        );

        setLastError(
          new UserFacingError(
            "Unable to sign you up",
            `We were unable to sign your account up in our systems. Please try again later, and if the issue persists, please contact ${SUPPORT_EMAIL}.`,
            err,
            err.body,
          ),
        );
      } else if (
        err instanceof Error &&
        err.message.toLowerCase().includes("recaptcha")
      ) {
        logger.error("Recaptcha failure during signup:", err);

        setLastError(
          new UserFacingError(
            "Recaptcha failure",
            `We were unable to successfully verify that you're human with Recaptcha due to an internal error. Please try again later, and if the issue persists, please contact ${SUPPORT_EMAIL}.`,
            err,
            err.message,
          ),
        );
      } else {
        logger.error("Unexpected error during signup:", err);

        setLastError(
          new UserFacingError(
            "Unable to sign you up",
            `An unexpected error occurred while setting up your account. Please try again later, and if the issue persists, please contact ${SUPPORT_EMAIL}.`,
            err,
            errorMessage(err),
          ),
        );
      }
    }
  }, [isUserAuthenticated, updateSignupPhase]);

  // Initial user fetch when the provider is mounted.
  useEffect(() => {
    // Don't fetch the user signup for unauthenticated users.
    if (!isUserAuthenticated) {
      updateSignupPhase(UserSignupPhase.UNAUTHENTICATED);
      return;
    }

    // Use a guard to avoid acting on stale requests.
    let cancelled = false;
    const controller = new AbortController();

    const doInitialFetch = async () => {
      try {
        // Try the bootstrapped promise first if we have one.
        if (bootstrapData.signupData) {
          const userSignup = await bootstrapData.signupData;
          if (cancelled) {
            return;
          }

          // Process the user signup.
          processSignupResult(userSignup, controller.signal);
          return;
        }
      } catch {
        // The bootstrap fetch failed, which is fine. Fall through to the
        // regular fetching with tries.
        if (cancelled) {
          return;
        }
      }

      // At this point either there was no bootstrap promise or it failed.
      // We fall back to the fetch-with-retry logic.
      await withRetry(
        () => fetchUser(controller.signal),
        3,
        3_000,
        isTransient,
        controller.signal,
      );
    };

    doInitialFetch().catch((error) => {
      if (cancelled) {
        return;
      }

      logger.error("Unable to obtain the user's signup information", error);

      updateSignupPhase(UserSignupPhase.BLOCKED);
      setLastError(mapFetchUserErrorToErrorMessage(error));
    });

    return () => {
      cancelled = true;
      controller.abort();
    };
  }, [
    bootstrapData.signupData,
    isUserAuthenticated,
    fetchUser,
    processSignupResult,
    updateSignupPhase,
  ]);

  // Determine if we should be polling to fetch the latest user data.
  const shouldBePolling = useMemo<boolean>(() => {
    // We definitely should not be polling if the user is unauthenticated.
    if (!isUserAuthenticated) {
      return false;
    }

    switch (userSignupPhase) {
      case UserSignupPhase.INITIAL_FETCH:
      case UserSignupPhase.NOT_STARTED:
      case UserSignupPhase.READY:
      default:
        return false;
      case UserSignupPhase.SIGNING_UP:
      case UserSignupPhase.PENDING_PHONE_VERIFICATION:
      case UserSignupPhase.PENDING_MANUAL_APPROVAL:
      case UserSignupPhase.PROVISIONING:
        return true;
    }
  }, [isUserAuthenticated, userSignupPhase]);

  // Determine the polling interval for the user data.
  const pollInterval = useMemo<number>(() => {
    // On development environments keep the interval short to ease
    // development.
    if (
      getConfig().environment === Environment.DEVELOPMENT ||
      getConfig().environment === Environment.DEVELOPMENT_KEYCLOAK
    ) {
      return SHORT_INTERVAL;
    }

    switch (userSignupPhase) {
      case UserSignupPhase.NOT_STARTED:
      case UserSignupPhase.PENDING_MANUAL_APPROVAL:
        return MEDIUM_INTERVAL;
      case UserSignupPhase.SIGNING_UP:
      case UserSignupPhase.PENDING_PHONE_VERIFICATION:
      case UserSignupPhase.PROVISIONING:
        return SHORT_INTERVAL;
      default:
        return MEDIUM_INTERVAL;
    }
  }, [userSignupPhase]);

  // Poll for the latest user data from the back end. In the case that the
  // user was in the process of being signed up, some notifications will be
  // shown to the user.
  useEffect(() => {
    if (!shouldBePolling) {
      return undefined;
    }

    let cancelled = false;
    const controller = new AbortController();
    const poll = async () => {
      // Capture the phase of the user signup before polling for the fresh
      // user data again.
      const wasSigningUp =
        userSignupPhaseRef.current === UserSignupPhase.SIGNING_UP ||
        userSignupPhaseRef.current === UserSignupPhase.PROVISIONING;

      // Refresh the user's signup.
      try {
        await fetchUser(controller.signal);
        if (cancelled) {
          return;
        }
        pollTransientRetriesLeft.current = maxTransientErrorRetries;
      } catch (error) {
        if (cancelled || isAbortError(error)) {
          return;
        }

        let technicalDetails: string | undefined;
        if (error instanceof ApiError) {
          if (isTransient(error) && pollTransientRetriesLeft.current > 0) {
            pollTransientRetriesLeft.current--;
            logger.warn(
              `Unexpected transient error received while polling on a user signup: ${error.body}`,
            );
          } else {
            cancelled = true;
            technicalDetails = error.body;
          }
        } else {
          cancelled = true;

          logger.error(
            `Unexpected error while polling for the user signup: ${error}`,
          );
          technicalDetails = errorMessage(error);
        }

        if (cancelled) {
          setLastError(
            new UserFacingError(
              "Unable to determine your account's status",
              `Unfortunately, we weren't able to determine your account's status. Please try again later, and if the issue persists, contact ${SUPPORT_EMAIL}.`,
              error,
              technicalDetails,
            ),
          );
        }
      }

      // If we were in the process of signing the user up, show a notification
      // to the user depending on their current state of their account.
      if (!cancelled && wasSigningUp) {
        // Make sure that after a significant amount of polling, we show some
        // feedback to the user if their account has not been provisioned.
        if (Date.now() - lastUserSignupPhaseChangedAt.current > 60_000) {
          setLastError(
            new UserFacingError(
              "Unable to set up your Developer Sandbox account",
              `We were unable to set up your Developer Sandbox account. Please contact support at ${SUPPORT_EMAIL}`,
              null,
              "The user was not provisioned after 60 seconds, and the polling for the user signup timed out",
            ),
          );

          updateSignupPhase(UserSignupPhase.PROVISIONING_TIMED_OUT);
          return;
        }
      }

      // Schedule a new timeout.
      if (!cancelled) {
        timerId = setTimeout(poll, pollInterval);
      }
    };

    let timerId = setTimeout(poll, pollInterval);
    return () => {
      cancelled = true;
      controller.abort();
      clearTimeout(timerId);
    };
  }, [fetchUser, pollInterval, shouldBePolling, updateSignupPhase]);

  // Memoize the contents of the context to avoid rerenders on any state or
  // function changes.
  const contextValue = useMemo(
    () => ({
      refetchUserData: fetchUser,
      signupUser,
      user,
      userError: lastError,
      userSignupPhase,
    }),
    [fetchUser, lastError, signupUser, user, userSignupPhase],
  );

  return (
    <UserContext.Provider value={contextValue}>{children}</UserContext.Provider>
  );
}
